config/routes.rb
Rails.application.routes.draw do
  #  # post '/auth/facebook/callback' => 'sessions#omniauthcreate'
  #  match '/auth/github/callback' => 'sessions#omniauthcreate', via: [:get, :post]
  #  # match '/auth/facebook/callback', to: 'sessions#omniauthcreate', via: [:get, :post]
  # root 'sessions#new'
  # resources :sessions
  # delete '/signout', to: 'sessions#destroy'

#resources :sessions, only: [:new, :create, :show]

  resources :spheres_goals
  
  resources :goals
  resources :spheres

  resources :users do
    resources :spheres 
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_many :spheres_goals
    has_many :spheres, through: :spheres_goals

    validates :title, presence: true
    validates :description, length: {maximum: 100}
    validates :sphere_ids, presence: true
  


    def get_sphere(current_goal_id)
        sphere_goal_var = current_goal_id.spheres_goal.where(goal_id == current_goal_id )
        sphere_goal_var.sphere_id
        
    end
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/sphere.rb
class Sphere < ApplicationRecord
    has_many :spheres_goals
    has_many :goals, through: :spheres_goals
    belongs_to :user

    validates :title, presence: true
    validates :title, uniqueness: true
end

app/models/spheres_goal.rb
class SpheresGoal < ApplicationRecord
    belongs_to :sphere
    belongs_to :goal
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :spheres

    validates :email, presence: true
    validates :name, presence: true
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
        
    
        def require_logged_in
            redirect_to controller: 'sessions', action: 'new' unless current_user 
          end
    
          def current_user
            User.find(session[:user_id])
        # session[:user_id] 
            end
    end
    

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
      @goal = Goal.new

      @spheres = current_user.spheres.all
  end

  def create
      @goal = Goal.new(goals_params)
      if @goal.valid?
      @goal.save
       redirect_to goal_path(@goal)
      else
          render :new
      end
  end
  def destroy
      @goal = Goal.find(params[:id])
      @goal.destroy
    
      sphere_id = SpheresGoal.find_by(goal_id: @goal.id).sphere_id
      redirect_to sphere_path(sphere_id) 
       
  end
  
  def edit
      @goal = Goal.find(params[:id])
    #   @spheres = current_user.spheres.all
    #   @current_user = current_user
  end

  def update
      @goal = Goal.find(params[:id])
      if @goal.update(goals_params)

      sphere_id = SpheresGoal.find_by(goal_id: @goal.id).sphere_id
      redirect_to sphere_path(sphere_id)
      else
          render :edit

      end
  end

  def show
      goal = Goal.find(params[:id])
      options = {
    include: [:spheres]
  }
      render json: GoalSerializer.new(goal, options)

  end
  def index
    goals = Goal.all
    options = {
    include: [:spheres]
  }
    render json: GoalSerializer.new(goals, options)
end
  private
  def goals_params
      params.require(:goal).permit(:title, :description, sphere_ids:[])
  end

end

app/controllers/spheres_controller.rb
class SpheresController < ApplicationController
  # before_action :require_logged_in
  def new
      
      user = User.find(params[:user_id])
     
      if user
        #&& user == current_user

          @sphere = user.spheres.build
          
      else 
          redirect_to '/'
          # render to error page
          # render "no user exists"
      end
  end

  def index
    spheres = Sphere.all
    render json: SphereSerializer.new(spheres)

  end

  def edit
      @sphere = Sphere.find(params[:id])
  end

  def update
  
      @sphere = Sphere.find(params[:id])
      if @sphere.update(sphere_params)
      redirect_to user_path(@sphere.user_id)
      else 
          render :edit
      end
  end

  def create
      @sphere = Sphere.new(sphere_params)
     if @sphere.valid?
      @sphere.save       
       redirect_to @sphere
     else 
      render :new

     end
          

  end

  
  def show
      sphere = Sphere.find(params[:id])
      options = {
    include: [:user, :goals]
  }
    #   # @user = current_user.id
    #   if sphere
    #       @sphere = sphere
    #   else
    #       # redirect_to user_path(current_user.id)
           
    #       render text: "No such sphere exists"
    #       # won't let me redirect for some reason
    #   end

    render json: SphereSerializer.new(sphere, options)
     
  end

  def destroy
      @sphere = Sphere.find(params[:id])
      @sphere.destroy
      user = @sphere.user_id
      # flash[:notice] = "Sphere deleted."
      redirect_to user_path(user)
      
  end
  private

  def sphere_params
      params.require(:sphere).permit(:title, :user_id)
  end
end

app/controllers/spheres_goals_controller.rb
class SpheresGoalsController < ApplicationController
  before_action :set_spheres_goal, only: %i[ show edit update destroy ]

  # GET /spheres_goals or /spheres_goals.json
  def index
    @spheres_goals = SpheresGoal.all
  end

  # GET /spheres_goals/1 or /spheres_goals/1.json
  def show
  end

  # GET /spheres_goals/new
  def new
    @spheres_goal = SpheresGoal.new
  end

  # GET /spheres_goals/1/edit
  def edit
  end

  # POST /spheres_goals or /spheres_goals.json
  def create
    @spheres_goal = SpheresGoal.new(spheres_goal_params)

    respond_to do |format|
      if @spheres_goal.save
        format.html { redirect_to spheres_goal_url(@spheres_goal), notice: "Spheres goal was successfully created." }
        format.json { render :show, status: :created, location: @spheres_goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spheres_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spheres_goals/1 or /spheres_goals/1.json
  def update
    respond_to do |format|
      if @spheres_goal.update(spheres_goal_params)
        format.html { redirect_to spheres_goal_url(@spheres_goal), notice: "Spheres goal was successfully updated." }
        format.json { render :show, status: :ok, location: @spheres_goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spheres_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spheres_goals/1 or /spheres_goals/1.json
  def destroy
    @spheres_goal.destroy

    respond_to do |format|
      format.html { redirect_to spheres_goals_url, notice: "Spheres goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spheres_goal
      @spheres_goal = SpheresGoal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spheres_goal_params
      params.require(:spheres_goal).permit(:goal_id, :sphere_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_logged_in
  # skip_before_action :require_logged_in, only: [:create, :new]

  def index
    users = User.all
    render json: UserSerializer.new(users)
  end

  def new
      @user = User.new

  end

  
  
  
  def show
      # raise params.inspect

      # if current_user.id.to_s == params[:id]
      
      @user = User.find(params[:id])
      render json: UserSerializer.new(@user)
      
      # raise current_user.inspect
      # else 
      #     redirect_to '/' 
      #     flash.now[:notice] = "the session hash's user instance does not match with the params user id"
      
      # end
  end
  
  def create
      @user = User.new(user_params)
      @user.save!
      # session[:user_id] = @user.id
      redirect_to user_path(@user)
  end
   private
  def user_params
          params.require(:user).permit!
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
    def spheres_helper
        current_user.spheres.all
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spheres_goals_helper.rb
module SpheresGoalsHelper
end

app/helpers/spheres_helper.rb
module SpheresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
        <% goal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<% if @goal.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<h1> Edit Goal </h1>
<%= form_for @goal do |f| %>
    <%= f.label "Title:" %><br>
    <%= f.text_field :title %><br>
  
    <%= f.label 'Description:' %><br>
    <%= f.text_area :description %><br>

    <%= f.collection_check_boxes :sphere_ids, spheres_helper, :id, :title %> <br>
  
    <%= f.submit %>
  <% end %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.title %></td>
        <td><%= goal.description %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<% if @goal.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<h1> Create a new Goal </h1>

<%= form_for @goal do |f| %>
    <label> Title: </label>
    <%= f.text_field :title %><br>

    <label> Description: </label>
    <%= f.text_field :description %><br>

    
    <%= f.collection_check_boxes :sphere_ids, spheres_helper, :id, :title %>

    <%= f.submit  %>

<% end %>

app/views/goals/show.html.erb
<h1> <%= "Name: #{@goal.title} "%> </h1>
<h2> <%= "Desc: #{@goal.description} " %> </h2>
<%= button_to "Delete #{@goal.title}", goal_path(@goal), method: :delete %>
<h3> Belonging to: </h3>

<ul> 
    <% @goal.spheres.each do |sphere| %>
        <li> 
             <h4> <%= link_to " #{sphere.title} Sphere", sphere_path(sphere) %>  </h4>
        </li>
        <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JanhaviRailsProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spheres/_form.html.erb
<%= form_with(model: sphere) do |form| %>
  <% if sphere.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sphere.errors.count, "error") %> prohibited this sphere from being saved:</h2>

      <ul>
        <% sphere.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :goal_aim %>
    <%= form.number_field :goal_aim %>
  </div>

  <div class="field">
    <%= form.label :aim_achieved %>
    <%= form.check_box :aim_achieved %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spheres/edit.html.erb
<% if @sphere.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @sphere.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @sphere do |f| %>
    <%= f.label "Sphere title:" %><br>
    <%= f.text_field :title %><br>
  
    <%= f.hidden_field :user_id %>
  
    <%= f.submit %>
  <% end %>

  

app/views/spheres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spheres</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Goal aim</th>
      <th>Aim achieved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spheres.each do |sphere| %>
      <tr>
        <td><%= sphere.title %></td>
        <td><%= sphere.user_id %></td>
        <td><%= sphere.goal_aim %></td>
        <td><%= sphere.aim_achieved %></td>
        <td><%= link_to 'Show', sphere %></td>
        <td><%= link_to 'Edit', edit_sphere_path(sphere) %></td>
        <td><%= link_to 'Destroy', sphere, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sphere', new_sphere_path %>

app/views/spheres/new.html.erb
<% if @sphere.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @sphere.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1> Create a New Sphere! </h1>

<%= form_for @sphere do |f|%>
    <label>Sphere title:</label><br>
    <%= f.text_field :title %><br>
    <%= f.hidden_field :user_id %>
     <%= f.submit "Create Sphere" %>
    
  <% end %>
  <%= link_to "Back to Homepage", user_path(@sphere.user_id) %>

app/views/spheres/show.html.erb
<% if @sphere.nil? %>
<%= link_to "You do not own such a Sphere. Click here to go back to your homepage", user_path(@user)%>

<% else %>


<h1> <%= "#{@sphere.title} Sphere" %> </h1>

<p> This is the show page for this Sphere </p>
<h4> <%= link_to "Go back to your homepage", user_path(@user) %> </h4>

<h2> Goals: </h2>
<ul>
    <% @sphere.goals.each do |goal| %>
        <li> <%= link_to "Title: #{goal.title}", goal_path(goal) %> <br>
         <%= "Description: #{goal.description}" %> </li>
         <%= button_to "Delete #{goal.title}", goal_path(goal), method: :delete %> <br>
         <%= link_to "Edit this goal", edit_goal_path(goal) %> <br>
    <% end %>
    

</ul>
<h3> <%= link_to "Create a new goal", new_goal_path %> </h3>
<% end %>

app/views/spheres_goals/_form.html.erb
<%= form_with(model: spheres_goal) do |form| %>
  <% if spheres_goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spheres_goal.errors.count, "error") %> prohibited this spheres_goal from being saved:</h2>

      <ul>
        <% spheres_goal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :goal_id %>
    <%= form.number_field :goal_id %>
  </div>

  <div class="field">
    <%= form.label :sphere_id %>
    <%= form.number_field :sphere_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spheres_goals/edit.html.erb
<h1>Editing Spheres Goal</h1>

<%= render 'form', spheres_goal: @spheres_goal %>

<%= link_to 'Show', @spheres_goal %> |
<%= link_to 'Back', spheres_goals_path %>

app/views/spheres_goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spheres Goals</h1>

<table>
  <thead>
    <tr>
      <th>Goal</th>
      <th>Sphere</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spheres_goals.each do |spheres_goal| %>
      <tr>
        <td><%= spheres_goal.goal_id %></td>
        <td><%= spheres_goal.sphere_id %></td>
        <td><%= link_to 'Show', spheres_goal %></td>
        <td><%= link_to 'Edit', edit_spheres_goal_path(spheres_goal) %></td>
        <td><%= link_to 'Destroy', spheres_goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spheres Goal', new_spheres_goal_path %>

app/views/spheres_goals/new.html.erb
<h1>New Spheres Goal</h1>

<%= render 'form', spheres_goal: @spheres_goal %>

<%= link_to 'Back', spheres_goals_path %>

app/views/spheres_goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @spheres_goal.goal_id %>
</p>

<p>
  <strong>Sphere:</strong>
  <%= @spheres_goal.sphere_id %>
</p>

<%= link_to 'Edit', edit_spheres_goal_path(@spheres_goal) %> |
<%= link_to 'Back', spheres_goals_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid %>
  </div>

  <div class="field">
    <%= form.label :provider %>
    <%= form.text_field :provider %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Password digest</th>
      <th>Uid</th>
      <th>Provider</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.uid %></td>
        <td><%= user.provider %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1> <%=" Welcome #{@user.name}!"%> </h1>
<% if @user.provider %>
<p> <%= " Authenticated by #{@user.provider.capitalize}, thanks to OmniAuth!" %> </p>

<% end %>
<h2> These are your spheres: <h2>
<ul>
    <% @user.spheres.each do |sphere| %>
        <li> 
            <%= link_to sphere.title, user_sphere_path(@user, sphere) %> <span/> <br> 
            <%= link_to "(Edit #{sphere.title})", edit_sphere_path(sphere) %>
            <%= button_to "Delete #{sphere.title}", sphere_path(sphere), method: :delete %>
        </li>
    <% end %>
</ul>


<p> <%= link_to "Log Out", signout_path, method: :delete %> </p>
<h3> <%= link_to "Create a new Sphere", new_user_sphere_path(@user) %> </h3>